name: Node.js CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run cdk:deploy
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-3'
          AWS_REGION: 'ap-northeast-3'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BLUSEKY_ID: ${{ secrets.BLUSEKY_ID }}
          BLUSEKY_PW: ${{ secrets.BLUSEKY_PW }}
          RSS_URL: ${{ secrets.RSS_URL }}
